In [1]:
import numpy as np
import pandas as pd
import os

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor

from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix


import warnings
warnings.filterwarnings("ignore")

In [2]:
folder_path = r'D:\SRM\4th_Year\hackathon\bob\ml_reccomendation'
csv_files = [f for f in os.listdir(folder_path) if f.endswith('.csv')]
csv_files

['custom_dataset.csv']

In [3]:
dataset=csv_files[0]
file_path = os.path.join(folder_path, dataset)
df = pd.read_csv(file_path)
df

,user_id,stock_symbol,amount_invested,purchase_time,purchase_price,sale_time,sale_price,profit_loss,Open,High,Low,Close,Open_sale,High_sale,Low_sale,Close_sale
0,13,AAPL,4233,2024-04-25,169.889999,2024-05-01,169.300003,-14.700421,169.529999,170.610001,168.149994,169.889999,169.580002,172.710007,169.110001,169.300003
1,85,AAPL,5385,2024-06-18,214.289993,2024-07-05,226.339996,302.810530,217.589996,218.630005,213.000000,214.289993,221.649994,226.449997,221.649994,226.339996
2,96,AAPL,7311,2024-07-16,234.820007,2024-07-18,224.179993,-331.271377,235.000000,236.270004,232.330002,234.820007,230.279999,230.440002,222.270004,224.179993
3,97,AAPL,5586,2024-06-13,214.240005,2024-07-22,223.960007,253.435051,214.740005,216.750000,211.600006,214.240005,227.009995,227.779999,223.089996,223.960007
4,68,AAPL,9581,2024-05-09,184.570007,2024-07-19,224.309998,2062.896632,182.559998,184.660004,182.110001,184.570007,224.820007,226.800003,223.279999,224.309998
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
985411,12,NVDA,3296,2024-05-15,94.629997,2024-05-16,94.359001,-9.438900,92.472000,94.862000,91.598999,94.629997,94.910004,95.819000,94.102997,94.359001
985412,63,NVDA,3561,2024-06-10,121.790001,2024-06-18,135.580002,403.203817,120.370003,123.099998,117.010002,121.790001,131.139999,136.330002,130.690002,135.580002
985413,80,NVDA,8634,2024-05-06,92.139999,2024-06-26,126.400002,3210.341441,89.389999,92.220001,89.055000,92.139999,126.129997,128.119995,122.599998,126.400002
985414,4,NVDA,7562,2024-05-01,83.041000,2024-05-23,103.799004,1890.295393,85.077003,86.000000,81.254997,83.041000,102.028000,106.320000,101.519997,103.799004
985415,43,NVDA,5683,2024-04-15,86.000999,2024-04-17,84.035004,-129.914235,89.098000,90.612999,85.929001,86.000999,88.339996,88.775002,83.949997,84.035004

In [4]:
df.describe()

,user_id,amount_invested,purchase_price,sale_price,profit_loss,Open,High,Low,Close,Open_sale,High_sale,Low_sale,Close_sale
count,985416.000000,985416.000000,985416.000000,985416.000000,985416.000000,985416.000000,985416.000000,985416.000000,985416.000000,985416.000000,985416.000000,985416.000000,985416.000000
mean,50.549449,5496.136430,260.885312,272.492816,321.805440,260.793779,263.886848,257.628656,260.885312,272.653998,275.978293,269.160428,272.492816
std,28.885395,2598.258516,181.046999,184.274981,715.657675,180.942312,182.929436,178.877611,181.046999,184.566820,186.562175,182.249859,184.274981
min,1.000000,1000.000000,29.850000,29.850000,-1737.813587,29.930000,30.150000,29.730000,29.850000,29.930000,30.150000,29.730000,29.850000
25%,26.000000,3248.000000,167.039993,172.600006,-20.954545,166.539993,168.059998,165.210007,167.039993,173.279999,174.750000,170.529999,172.600006
50%,51.000000,5498.000000,183.250000,189.720001,122.708084,183.660004,185.149994,181.490005,183.250000,189.850006,191.360001,186.929993,189.720001
75%,76.000000,7745.000000,427.000000,443.519989,435.250194,425.480011,428.079987,423.000000,427.000000,444.339996,444.850006,439.179993,443.519989
max,100.000000,10000.000000,690.650024,690.650024,8313.332297,690.000000,697.489990,684.719971,690.650024,690.000000,697.489990,684.719971,690.650024

In [5]:
df.dtypes

user_id              int64
stock_symbol        object
amount_invested      int64
purchase_time       object
purchase_price     float64
sale_time           object
sale_price         float64
profit_loss        float64
Open               float64
High               float64
Low                float64
Close              float64
Open_sale          float64
High_sale          float64
Low_sale           float64
Close_sale         float64
dtype: object

In [6]:
df['purchase_time'] = pd.to_datetime(df['purchase_time'])
df['sale_time'] = pd.to_datetime(df['sale_time'])
df.dtypes

user_id                     int64
stock_symbol               object
amount_invested             int64
purchase_time      datetime64[ns]
purchase_price            float64
sale_time          datetime64[ns]
sale_price                float64
profit_loss               float64
Open                      float64
High                      float64
Low                       float64
Close                     float64
Open_sale                 float64
High_sale                 float64
Low_sale                  float64
Close_sale                float64
dtype: object

In [7]:
df.isnull().sum()

user_id            0
stock_symbol       0
amount_invested    0
purchase_time      0
purchase_price     0
sale_time          0
sale_price         0
profit_loss        0
Open               0
High               0
Low                0
Close              0
Open_sale          0
High_sale          0
Low_sale           0
Close_sale         0
dtype: int64

#### Feature Engineering :
Converting these dates into numbers(day of week) that can show patterns over time.

In [8]:
df['profit_loss'] = (df['sale_price'] - df['purchase_price']) / df['purchase_price']

df['purchase_day'] = df['purchase_time'].dt.dayofweek
df['sale_day'] = df['sale_time'].dt.dayofweek

df['stock_sign'] = np.where(df['profit_loss'] > 0, 1, 0)
df

,user_id,stock_symbol,amount_invested,purchase_time,purchase_price,sale_time,sale_price,profit_loss,Open,High,Low,Close,Open_sale,High_sale,Low_sale,Close_sale,purchase_day,sale_day,stock_sign
0,13,AAPL,4233,2024-04-25,169.889999,2024-05-01,169.300003,-0.003473,169.529999,170.610001,168.149994,169.889999,169.580002,172.710007,169.110001,169.300003,3,2,0
1,85,AAPL,5385,2024-06-18,214.289993,2024-07-05,226.339996,0.056232,217.589996,218.630005,213.000000,214.289993,221.649994,226.449997,221.649994,226.339996,1,4,1
2,96,AAPL,7311,2024-07-16,234.820007,2024-07-18,224.179993,-0.045311,235.000000,236.270004,232.330002,234.820007,230.279999,230.440002,222.270004,224.179993,1,3,0
3,97,AAPL,5586,2024-06-13,214.240005,2024-07-22,223.960007,0.045370,214.740005,216.750000,211.600006,214.240005,227.009995,227.779999,223.089996,223.960007,3,0,1
4,68,AAPL,9581,2024-05-09,184.570007,2024-07-19,224.309998,0.215311,182.559998,184.660004,182.110001,184.570007,224.820007,226.800003,223.279999,224.309998,3,4,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
985411,12,NVDA,3296,2024-05-15,94.629997,2024-05-16,94.359001,-0.002864,92.472000,94.862000,91.598999,94.629997,94.910004,95.819000,94.102997,94.359001,2,3,0
985412,63,NVDA,3561,2024-06-10,121.790001,2024-06-18,135.580002,0.113228,120.370003,123.099998,117.010002,121.790001,131.139999,136.330002,130.690002,135.580002,0,1,1
985413,80,NVDA,8634,2024-05-06,92.139999,2024-06-26,126.400002,0.371826,89.389999,92.220001,89.055000,92.139999,126.129997,128.119995,122.599998,126.400002,0,2,1
985414,4,NVDA,7562,2024-05-01,83.041000,2024-05-23,103.799004,0.249973,85.077003,86.000000,81.254997,83.041000,102.028000,106.320000,101.519997,103.799004,2,3,1
985415,43,NVDA,5683,2024-04-15,86.000999,2024-04-17,84.035004,-0.022860,89.098000,90.612999,85.929001,86.000999,88.339996,88.775002,83.949997,84.035004,0,2,0

##### Dividing the datasets based on stocks:

In [9]:
stock_symbols = sorted(df['stock_symbol'].unique())

stock_dfs = {}

for symbol in stock_symbols:
    stock_dfs[symbol] = df[df['stock_symbol'] == symbol]

for symbol in stock_symbols:
    print(f"{symbol}: {len(stock_dfs[symbol])} records.")

AAPL: 98491 records.
AMZN: 98599 records.
GOOGL: 98518 records.
IBM: 98599 records.
INTC: 98572 records.
META: 98560 records.
MSFT: 98483 records.
NFLX: 98533 records.
NVDA: 98557 records.
TSLA: 98504 records.

In [10]:
stock_dfs["AAPL"]

,user_id,stock_symbol,amount_invested,purchase_time,purchase_price,sale_time,sale_price,profit_loss,Open,High,Low,Close,Open_sale,High_sale,Low_sale,Close_sale,purchase_day,sale_day,stock_sign
0,13,AAPL,4233,2024-04-25,169.889999,2024-05-01,169.300003,-0.003473,169.529999,170.610001,168.149994,169.889999,169.580002,172.710007,169.110001,169.300003,3,2,0
1,85,AAPL,5385,2024-06-18,214.289993,2024-07-05,226.339996,0.056232,217.589996,218.630005,213.000000,214.289993,221.649994,226.449997,221.649994,226.339996,1,4,1
2,96,AAPL,7311,2024-07-16,234.820007,2024-07-18,224.179993,-0.045311,235.000000,236.270004,232.330002,234.820007,230.279999,230.440002,222.270004,224.179993,1,3,0
3,97,AAPL,5586,2024-06-13,214.240005,2024-07-22,223.960007,0.045370,214.740005,216.750000,211.600006,214.240005,227.009995,227.779999,223.089996,223.960007,3,0,1
4,68,AAPL,9581,2024-05-09,184.570007,2024-07-19,224.309998,0.215311,182.559998,184.660004,182.110001,184.570007,224.820007,226.800003,223.279999,224.309998,3,4,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98486,31,AAPL,2499,2024-06-20,209.679993,2024-06-25,209.070007,-0.002909,213.929993,214.240005,208.850006,209.679993,209.149994,211.380005,208.610001,209.070007,3,1,0
98487,1,AAPL,4520,2024-05-24,189.979996,2024-06-28,210.619995,0.108643,188.820007,190.580002,188.039993,189.979996,215.770004,216.070007,210.300003,210.619995,4,4,1
98488,30,AAPL,6955,2024-06-07,196.889999,2024-07-18,224.179993,0.138605,194.649994,196.940002,194.139999,196.889999,230.279999,230.440002,222.270004,224.179993,4,3,1
98489,54,AAPL,9867,2024-05-01,169.300003,2024-05-30,191.289993,0.129888,169.580002,172.710007,169.110001,169.300003,190.759995,192.179993,190.630005,191.289993,2,3,1
98490,68,AAPL,6223,2024-04-22,165.839996,2024-05-03,183.380005,0.105765,165.520004,167.259995,164.770004,165.839996,186.649994,187.000000,182.660004,183.380005,0,4,1

In [11]:
def train_and_predict(stock_df, investment_amount):
    features = ['amount_invested', 'purchase_price', 'Open', 'High', 'Low', 'Close', 'Open_sale', 'High_sale', 'Low_sale', 'Close_sale', 'purchase_day', 'sale_day', 'stock_sign']
    target = 'profit_loss'

    if len(stock_df) < 2:
        return None

    stock_df['amount_invested'] = investment_amount  # Use the investment amount for retraining

    X = stock_df[features]
    y = stock_df[target]

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
    model = DecisionTreeRegressor(random_state=42)
    model.fit(X_train, y_train)

    y_pred = model.predict(X_test)
    predicted_profit_loss = y_pred.mean()

    return predicted_profit_loss

results_df = pd.DataFrame(columns=['stock_symbol', 'predicted_profit_loss'])

investment_amount = float(input("Enter the amount you want to invest: "))

for symbol in stock_symbols:
    stock_df = df[df['stock_symbol'] == symbol]
    predicted_profit_loss = train_and_predict(stock_df, investment_amount)

    if predicted_profit_loss is not None:
        results_df = results_df.append({'stock_symbol': symbol, 'predicted_profit_loss': predicted_profit_loss}, ignore_index=True)

results_df['predicted_profit_loss_amount'] = results_df['predicted_profit_loss'] * investment_amount
results_df['predicted_profit_loss_amount'] = results_df['predicted_profit_loss_amount'].round(2)
results_df.sort_values(by='predicted_profit_loss_amount', ascending=False, inplace=True)

print("\nResults DataFrame with Investment Amount:")
print(results_df)

Enter the amount you want to invest: 500000

Results DataFrame with Investment Amount:
  stock_symbol  predicted_profit_loss  predicted_profit_loss_amount
9         TSLA               0.158682                      79341.16
8         NVDA               0.141604                      70802.08
0         AAPL               0.096920                      48459.76
2        GOOGL               0.039379                      19689.50
7         NFLX               0.038028                      19013.87
6         MSFT               0.035295                      17647.59
3          IBM               0.021305                      10652.68
5         META               0.020283                      10141.70
1         AMZN               0.017506                       8752.92
4         INTC               0.016832                       8415.84

In [12]:
import pandas as pd
import pickle
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor

def train_and_predict(stock_df, investment_amount, model_filename):
    features = ['amount_invested', 'purchase_price', 'Open', 'High', 'Low', 'Close', 'Open_sale', 'High_sale', 'Low_sale', 'Close_sale', 'purchase_day', 'sale_day', 'stock_sign']
    target = 'profit_loss'

    if len(stock_df) < 2:
        return None

    stock_df['amount_invested'] = investment_amount  # Use the investment amount for retraining

    X = stock_df[features]
    y = stock_df[target]

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
    model = DecisionTreeRegressor(random_state=42)
    model.fit(X_train, y_train)

    # Save the model to a file
    with open(model_filename, 'wb') as f:
        pickle.dump(model, f)

    y_pred = model.predict(X_test)
    predicted_profit_loss = y_pred.mean()

    return predicted_profit_loss

results_df = pd.DataFrame(columns=['stock_symbol', 'predicted_profit_loss'])

investment_amount = float(input("Enter the amount you want to invest: "))

model_filename = 'stock_model.pkl'

for symbol in stock_symbols:
    stock_df = df[df['stock_symbol'] == symbol]
    predicted_profit_loss = train_and_predict(stock_df, investment_amount, model_filename)

    if predicted_profit_loss is not None:
        results_df = results_df.append({'stock_symbol': symbol, 'predicted_profit_loss': predicted_profit_loss}, ignore_index=True)

results_df['predicted_profit_loss_amount'] = results_df['predicted_profit_loss'] * investment_amount
results_df['predicted_profit_loss_amount'] = results_df['predicted_profit_loss_amount'].round(2)
results_df.sort_values(by='predicted_profit_loss_amount', ascending=False, inplace=True)

print("\nResults DataFrame with Investment Amount:")
print(results_df)

Enter the amount you want to invest: 50000

Results DataFrame with Investment Amount:
  stock_symbol  predicted_profit_loss  predicted_profit_loss_amount
9         TSLA               0.158682                       7934.12
8         NVDA               0.141604                       7080.21
0         AAPL               0.096920                       4845.98
2        GOOGL               0.039379                       1968.95
7         NFLX               0.038028                       1901.39
6         MSFT               0.035295                       1764.76
3          IBM               0.021305                       1065.27
5         META               0.020283                       1014.17
1         AMZN               0.017506                        875.29
4         INTC               0.016832                        841.58

In [15]:
import pandas as pd
import pickle
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor

def train_and_predict(stock_df, investment_amount, model_filename):
    features = ['amount_invested', 'purchase_price', 'Open', 'High', 'Low', 'Close', 'Open_sale', 'High_sale', 'Low_sale', 'Close_sale', 'purchase_day', 'sale_day', 'stock_sign']
    target = 'profit_loss'

    if len(stock_df) < 2:
        return None

    stock_df['amount_invested'] = investment_amount  # Use the investment amount for retraining

    X = stock_df[features]
    y = stock_df[target]

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
    model = DecisionTreeRegressor(random_state=42)
    model.fit(X_train, y_train)

    # Save the model to a file
    with open(model_filename, 'wb') as f:
        pickle.dump(model, f)

    y_pred = model.predict(X_test)
    predicted_profit_loss = y_pred.mean()

    return predicted_profit_loss

results_df = pd.DataFrame(columns=['stock_symbol', 'predicted_profit_loss'])

investment_amount = float(input("Enter the amount you want to invest: "))

model_filename = 'stock_model.pkl'

for symbol in stock_symbols:
    stock_df = df[df['stock_symbol'] == symbol]
    predicted_profit_loss = train_and_predict(stock_df, investment_amount, model_filename)

    if predicted_profit_loss is not None:
        results_df = results_df.append({'stock_symbol': symbol, 'predicted_profit_loss': predicted_profit_loss}, ignore_index=True)

results_df['predicted_profit_loss_amount'] = results_df['predicted_profit_loss'] * investment_amount
results_df['predicted_profit_loss_amount'] = results_df['predicted_profit_loss_amount'].round(2)
results_df.sort_values(by='predicted_profit_loss_amount', ascending=False, inplace=True)

print("\nResults DataFrame with Investment Amount:")
print(results_df)

Enter the amount you want to invest: 109642.375756

Results DataFrame with Investment Amount:
  stock_symbol  predicted_profit_loss  predicted_profit_loss_amount
9         TSLA               0.158682                      17398.31
8         NVDA               0.141604                      15525.82
0         AAPL               0.096920                      10626.49
2        GOOGL               0.039379                       4317.61
7         NFLX               0.038028                       4169.45
6         MSFT               0.035295                       3869.85
3          IBM               0.021305                       2335.97
5         META               0.020283                       2223.92
1         AMZN               0.017506                       1919.38
4         INTC               0.016832                       1845.46

In [16]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor
from joblib import dump, load

def train_and_predict(stock_df, investment_amount, model_filename):
    features = ['amount_invested', 'purchase_price', 'Open', 'High', 'Low', 'Close', 'Open_sale', 'High_sale', 'Low_sale', 'Close_sale', 'purchase_day', 'sale_day', 'stock_sign']
    target = 'profit_loss'

    if len(stock_df) < 2:
        return None

    stock_df['amount_invested'] = investment_amount  # Use the investment amount for retraining

    X = stock_df[features]
    y = stock_df[target]

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
    model = DecisionTreeRegressor(random_state=42)
    model.fit(X_train, y_train)

    # Save the model to a file
    dump(model, model_filename)

    y_pred = model.predict(X_test)
    predicted_profit_loss = y_pred.mean()

    return predicted_profit_loss

results_df = pd.DataFrame(columns=['stock_symbol', 'predicted_profit_loss'])

investment_amount = float(input("Enter the amount you want to invest: "))

model_filename = 'stock_model.joblib'

for symbol in stock_symbols:
    stock_df = df[df['stock_symbol'] == symbol]
    predicted_profit_loss = train_and_predict(stock_df, investment_amount, model_filename)

    if predicted_profit_loss is not None:
        results_df = results_df.append({'stock_symbol': symbol, 'predicted_profit_loss': predicted_profit_loss}, ignore_index=True)

results_df['predicted_profit_loss_amount'] = results_df['predicted_profit_loss'] * investment_amount
results_df['predicted_profit_loss_amount'] = results_df['predicted_profit_loss_amount'].round(2)
results_df.sort_values(by='predicted_profit_loss_amount', ascending=False, inplace=True)

print("\nResults DataFrame with Investment Amount:")
print(results_df)

The history saving thread hit an unexpected error (OperationalError('database or disk is full')).History will not be written to the database.
Enter the amount you want to invest: 5000

Results DataFrame with Investment Amount:
  stock_symbol  predicted_profit_loss  predicted_profit_loss_amount
9         TSLA               0.158682                        793.41
8         NVDA               0.141604                        708.02
0         AAPL               0.096920                        484.60
2        GOOGL               0.039379                        196.90
7         NFLX               0.038028                        190.14
6         MSFT               0.035295                        176.48
3          IBM               0.021305                        106.53
5         META               0.020283                        101.42
1         AMZN               0.017506                         87.53
4         INTC               0.016832                         84.16

In [14]:
def load_model_and_predict(model_filename, stock_df, investment_amount):
    features = ['amount_invested', 'purchase_price', 'Open', 'High', 'Low', 'Close', 'Open_sale', 'High_sale', 'Low_sale', 'Close_sale', 'purchase_day', 'sale_day', 'stock_sign']

    with open(model_filename, 'rb') as f:
        model = pickle.load(f)

    stock_df['amount_invested'] = investment_amount
    X_new = stock_df[features]

    y_pred_new = model.predict(X_new)
    predicted_profit_loss_new = y_pred_new.mean()

    predicted_profit_loss_amount_new = predicted_profit_loss_new * investment_amount
    predicted_profit_loss_amount_new = round(predicted_profit_loss_amount_new, 2)

    return predicted_profit_loss_new, predicted_profit_loss_amount_new

new_investment_amount = float(input("Enter the new amount you want to invest: "))

for symbol in stock_symbols:
    stock_df = df[df['stock_symbol'] == symbol]
    predicted_profit_loss_new, predicted_profit_loss_amount_new = load_model_and_predict(model_filename, stock_df, new_investment_amount)

    print(f"\nPredicted profit/loss for stock {symbol} with new investment amount {new_investment_amount}: {predicted_profit_loss_new}")
    print(f"Predicted profit/loss amount for stock {symbol} with new investment amount {new_investment_amount}: {predicted_profit_loss_amount_new}")

Enter the new amount you want to invest: 500000

Predicted profit/loss for stock AAPL with new investment amount 500000.0: 0.1005757605836037
Predicted profit/loss amount for stock AAPL with new investment amount 500000.0: 50287.88

Predicted profit/loss for stock AMZN with new investment amount 500000.0: 0.03478287964216399
Predicted profit/loss amount for stock AMZN with new investment amount 500000.0: 17391.44

Predicted profit/loss for stock GOOGL with new investment amount 500000.0: 0.050535272631397656
Predicted profit/loss amount for stock GOOGL with new investment amount 500000.0: 25267.64

Predicted profit/loss for stock IBM with new investment amount 500000.0: 0.03173992456266767
Predicted profit/loss amount for stock IBM with new investment amount 500000.0: 15869.96

Predicted profit/loss for stock INTC with new investment amount 500000.0: -0.01814829702231482
Predicted profit/loss amount for stock INTC with new investment amount 500000.0: -9074.15

Predicted profit/loss for stock META with new investment amount 500000.0: -0.005313876932876616
Predicted profit/loss amount for stock META with new investment amount 500000.0: -2656.94

Predicted profit/loss for stock MSFT with new investment amount 500000.0: 0.000812846913064992
Predicted profit/loss amount for stock MSFT with new investment amount 500000.0: 406.42

Predicted profit/loss for stock NFLX with new investment amount 500000.0: -0.0027935611122310126
Predicted profit/loss amount for stock NFLX with new investment amount 500000.0: -1396.78

Predicted profit/loss for stock NVDA with new investment amount 500000.0: -0.0049952187528615535
Predicted profit/loss amount for stock NVDA with new investment amount 500000.0: -2497.61

Predicted profit/loss for stock TSLA with new investment amount 500000.0: 0.1586209303649793
Predicted profit/loss amount for stock TSLA with new investment amount 500000.0: 79310.47

In [4]:
import joblib
import numpy as np
import pandas as pd

# Function to load the model
def load_model():
    model = joblib.load("stock_model.joblib")
    return model

# Function to preprocess input data
def preprocess_data(investment_amount):
    data = {
        'amount_invested': [investment_amount],
        'purchase_price': [500.0],   # Example values
        'Open': [505.0],             # Example values
        'High': [510.0],             # Example values
        'Low': [500.0],              # Example values
        'Close': [508.0],            # Example values
        'Open_sale': [510.0],        # Example values
        'High_sale': [515.0],        # Example values
        'Low_sale': [505.0],         # Example values
        'Close_sale': [512.0],       # Example values
        'purchase_day': [1],         # Example values
        'sale_day': [5],             # Example values
        'stock_sign': ['AAPL']       # Example values
    }
    df = pd.DataFrame(data)
    return df

# Function to make a prediction
def predict(investment_amount):
    model = load_model()
    input_data = preprocess_data(investment_amount)
    prediction = model.predict(input_data)
    return prediction[0]

# Use an example investment amount for prediction
investment_amount = 5000.0
result = predict(investment_amount)
print(f"Predicted profit/loss for an investment amount of {investment_amount} is: {result}")

In [9]:
import joblib
import numpy as np
import pandas as pd
from IPython.display import display
from ipywidgets import widgets
from sklearn.preprocessing import LabelEncoder

# Function to load the model
def load_model():
    model = joblib.load("stock_model.joblib")
    return model

# Function to preprocess input data
def preprocess_data(investment_amount):
    data = {
        'amount_invested': [investment_amount],
        'purchase_price': [500.0],   # Example values
        'Open': [505.0],             # Example values
        'High': [510.0],             # Example values
        'Low': [500.0],              # Example values
        'Close': [508.0],            # Example values
        'Open_sale': [510.0],        # Example values
        'High_sale': [515.0],        # Example values
        'Low_sale': [505.0],         # Example values
        'Close_sale': [512.0],       # Example values
        'purchase_day': [1],         # Example values
        'sale_day': [5],             # Example values
        'stock_sign': ['AAPL']       # Example values
    }
    df = pd.DataFrame(data)

    # Encoding the categorical feature 'stock_sign'
    le = LabelEncoder()
    df['stock_sign'] = le.fit_transform(df['stock_sign'])

    return df

# Function to make a prediction
def predict(investment_amount):
    model = load_model()
    input_data = preprocess_data(investment_amount)
    prediction = model.predict(input_data)
    return prediction[0]

# Function to handle button click
def on_button_click(b):
    investment_amount = float(investment_amount_widget.value)
    result = predict(investment_amount)
    predicted_profit_loss_amount_new =result* investment_amount
    predicted_profit_loss_amount_new = round(predicted_profit_loss_amount_new, 2)

    print(f"Predicted profit/loss for an investment amount of {investment_amount} is: {result}")
    print(f"Amount of profit/loss wrt actual amount :{predicted_profit_loss_amount_new}")
# Widgets for interactive input
investment_amount_widget = widgets.FloatText(
    value=5000.0,
    description='Investment Amount:',
    disabled=False
)

button = widgets.Button(
    description='Predict',
    disabled=False,
    button_style='',
    tooltip='Click to make a prediction',
    icon='check'
)

button.on_click(on_button_click)

display(investment_amount_widget)
display(button)

FloatText(value=5000.0, description='Investment Amount:')

Button(description='Predict', icon='check', style=ButtonStyle(), tooltip='Click to make a prediction')

Predicted profit/loss for an investment amount of 5000.0 is: -0.040340385861989965
Amount of profit/loss wrt actual amount :-201.7

In [10]:
import joblib
import numpy as np
import pandas as pd
from IPython.display import display
from ipywidgets import widgets
from sklearn.preprocessing import LabelEncoder
import sys

# Function to load the model
def load_model():
    model = joblib.load("stock_model.joblib")
    return model

# Function to preprocess input data
def preprocess_data(investment_amount):
    data = {
        'amount_invested': [investment_amount],
        'purchase_price': [500.0],   # Example values
        'Open': [505.0],             # Example values
        'High': [510.0],             # Example values
        'Low': [500.0],              # Example values
        'Close': [508.0],            # Example values
        'Open_sale': [510.0],        # Example values
        'High_sale': [515.0],        # Example values
        'Low_sale': [505.0],         # Example values
        'Close_sale': [512.0],       # Example values
        'purchase_day': [1],         # Example values
        'sale_day': [5],             # Example values
        'stock_sign': ['AAPL']       # Example values
    }
    df = pd.DataFrame(data)

    # Encoding the categorical feature 'stock_sign'
    le = LabelEncoder()
    df['stock_sign'] = le.fit_transform(df['stock_sign'])

    return df

# Function to make a prediction
def predict(investment_amount):
    model = load_model()
    input_data = preprocess_data(investment_amount)
    prediction = model.predict(input_data)
    return prediction[0]

# Function to handle button click
def on_button_click(b):
    investment_amount = float(investment_amount_widget.value)
    result = predict(investment_amount)
    predicted_profit_loss_amount_new = result * investment_amount
    predicted_profit_loss_amount_new = round(predicted_profit_loss_amount_new, 2)

    print(f"Predicted profit/loss for an investment amount of {investment_amount} is: {result}")
    print(f"Amount of profit/loss with respect to actual amount: {predicted_profit_loss_amount_new}")

# Widgets for interactive input
def interactive_mode():
    investment_amount_widget = widgets.FloatText(
        value=5000.0,
        description='Investment Amount:',
        disabled=False
    )

    button = widgets.Button(
        description='Predict',
        disabled=False,
        button_style='',
        tooltip='Click to make a prediction',
        icon='check'
    )

    button.on_click(on_button_click)

    display(investment_amount_widget)
    display(button)

# Command-line mode
def command_line_mode():
    if len(sys.argv) < 2:
        print("Usage: python stock_prediction.py <investment_amount>")
        sys.exit(1)

    investment_amount = float(sys.argv[1])
    result = predict(investment_amount)
    print(f"Predicted profit/loss for an investment amount of {investment_amount} is: {result}")

if __name__ == "__main__":
    # Check if running in Jupyter Notebook or a similar interactive environment
    try:
        from IPython import get_ipython
        if get_ipython() is not None:
            interactive_mode()
        else:
            command_line_mode()
    except ImportError:
        # Fallback to command-line mode if IPython is not available
        command_line_mode()

FloatText(value=5000.0, description='Investment Amount:')

Button(description='Predict', icon='check', style=ButtonStyle(), tooltip='Click to make a prediction')

Predicted profit/loss for an investment amount of 5000.0 is: -0.040340385861989965
Amount of profit/loss with respect to actual amount: -201.7